language: php

php:
  - 5.3.8
  - 5.4

branches:
  only:
    - master
    - develop

env:
  - TESTING_FRAMEWORK=PHPUnit
  - TESTING_FRAMEWORK=Behat

before_install:
 - sh install-phar.sh
 - php onion.phar bundle
script: sh run-test.sh
