language: php

php:
  - 5.3
  - 5.4

branches:
  only:
    - master
    - develop

env:
  - TESTING_FRAMEWORK=PHPUnit
  - TESTING_FRAMEWORK=Behat

before_script: sh install.sh

script: sh run-test.sh
